// array to store color
var buttonColors=["red", "blue", "green", "yellow"];

// array of random colours generated by computer
var gamePattern=[];

// array of colours clicked by user
var userClickedPattern=[];

var started = false;
var level = 0;

$(document).keydown(function(){
    if(!started){
        $("#level-title").text("Level "+level);
        nextSequence();
        started = true;
    }
});

// colours, effect, sound, push by user
$(".btn").click(function(event){
    var userChoosenColour = $(this).attr("id");
    userClickedPattern.push(userChoosenColour);

    console.log(userClickedPattern);

    playSound(userChoosenColour);
    animatePress(userChoosenColour);

    checkAnswer(userClickedPattern.length-1);
});

// colour, effects, sound by computer. Pushing colour to array
function nextSequence(){
    userClickedPattern = [];

    level++;
    $("#level-title").text("Level "+level);
    
    var n = Math.floor(Math.random()*4);
    var randomChosenColour = buttonColors[n];
    gamePattern.push(randomChosenColour);
    console.log(gamePattern);

    $("#"+randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
    playSound(randomChosenColour);
    animatePress(randomChosenColour);
}

for(var i=0;i<gamePattern.length();i++){
    if(gamePattern[i] !== userClickedPattern[i]){
        $("#level-title").text("Wrong answer");
        level=0;
    }
}

function checkAnswer(currentlevel){
    if(userClickedPattern[currentlevel] === gamePattern[currentlevel]){
        if(currentlevel === gamePattern.length - 1){
            setTimeout(function(){
                nextSequence();
            },1000);
        }
    }
    else{
        playSound("wrong");
        $("body").addClass("game-over");
        setTimeout(function(){
            $("body").removeClass("game-over");
        }, 200);
        $("#level-title").text("Game Over, Press Any Key to Restart");
        startOver();
    }
}

function startOver(){
    level = 0;
    gamePattern =[];
    started = false;
}

//utility functions
function playSound(name){
    var audio = new Audio("sounds/"+name+".mp3");
    audio.play();
}

function animatePress(currentColour){
    $("."+currentColour).addClass("pressed");
    setTimeout(function(){
        $("."+currentColour).removeClass("pressed");
    },100);
}





















//  below is my way of adding sound to selected btn(par isme click kr kr sound aa raha):-
//             |
//             v
// document.querySelector("."+randomChosenColour).addEventListener("click", function(){
//     sound(this.innerText);
// });


// function sound(keyName){
// switch(keyName){
//     case "blue":
//         var audio = new Audio("sounds/blue.mp3");
//         audio.play();
//         break;
//     case "green":
//         var audio = new Audio("sounds/green.mp3");
//         audio.play();
//         break;
//     case "red":
//         var audio = new Audio("sounds/red.mp3");
//         audio.play();
//         break;
//     case "yellow":
//         var audio = new Audio("sounds/yellow.mp3");
//         audio.play();
//         break;
//     default:
//         console.log(this);
//         break;
//     }

// }